# site settings
title: Forty
subtitle: by HTML5 UP
email: nell.djmf@gmail.com
description: Full stack software engineer with a background in healthcare <br /> Book worm || Lover of all things cute.
baseurl: "/portfolio" # the subpath of your site, e.g. /blog
url: https://nell-djmf.github.io
author:
street_address: 73 Park Brook Gdns
city: Middlesex
state: NJ
zip_code: 08846
country: United States of America
phone: (201) 895-8813

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/nell-djmf
  GitLab:
  Google-Plus:
  Instagram:
  LinkedIn: https://www.linkedin.com/in/nellf/
  Twitter:
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
  - "*.gemspec"
  - LICENSE.md
  - CONTRIBUTING.md
  - README.md
